# Generated by Django 2.0.6 on 2018-06-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affix_tupe', models.IntegerField()),
                ('affix_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_level', models.IntegerField(default=0)),
                ('item_tupe', models.IntegerField()),
                ('item_rarity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='affix',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
