# Generated by Django 2.0.6 on 2018-06-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bought', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_out', models.IntegerField()),
                ('next_bid', models.IntegerField()),
                ('biddable', models.BooleanField()),
                ('end_time', models.DateTimeField()),
                ('character_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Character')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='loot',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
        migrations.AddField(
            model_name='bid',
            name='character_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Character'),
        ),
        migrations.AddField(
            model_name='bid',
            name='loot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Loot'),
        ),
        migrations.AddField(
            model_name='auctionlog',
            name='character_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Character'),
        ),
        migrations.AddField(
            model_name='item',
            name='character_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Character'),
        ),
    ]
