# Generated by Django 2.0.6 on 2018-06-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180616_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affix',
            name='affix_tupe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='affix',
            name='affix_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='affix',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
        migrations.AlterField(
            model_name='auctionlog',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctionlog',
            name='character_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Character'),
        ),
        migrations.AlterField(
            model_name='auctionlog',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctionlog',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='character_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Character'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='loot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Loot'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_rarity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_tupe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loot',
            name='biddable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loot',
            name='buy_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loot',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loot',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='next_bid',
            field=models.IntegerField(default=0),
        ),
    ]
