# Generated by Django 2.0.6 on 2018-06-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlog',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
