# Generated by Django 2.0.6 on 2018-06-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auctionlog_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
